// Mocks generated by Mockito 5.4.4 from annotations
// in piano_tool/test/ui/levels/level_list_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:piano_tool/data/progress_repository.dart' as _i2;
import 'package:piano_tool/models/level_models.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ProgressRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProgressRepository extends _i1.Mock
    implements _i2.ProgressRepository {
  MockProgressRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.StageProgress?> read(String? stageId) => (super.noSuchMethod(
        Invocation.method(
          #read,
          [stageId],
        ),
        returnValue: _i3.Future<_i4.StageProgress?>.value(),
      ) as _i3.Future<_i4.StageProgress?>);

  @override
  _i3.Future<Map<String, _i4.StageProgress>> readAll() => (super.noSuchMethod(
        Invocation.method(
          #readAll,
          [],
        ),
        returnValue: _i3.Future<Map<String, _i4.StageProgress>>.value(
            <String, _i4.StageProgress>{}),
      ) as _i3.Future<Map<String, _i4.StageProgress>>);

  @override
  _i3.Future<void> record({
    required String? stageId,
    required double? accuracy,
    required int? score,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #record,
          [],
          {
            #stageId: stageId,
            #accuracy: accuracy,
            #score: score,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> lastPlayedStageId() => (super.noSuchMethod(
        Invocation.method(
          #lastPlayedStageId,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> setLastPlayed(String? stageId) => (super.noSuchMethod(
        Invocation.method(
          #setLastPlayed,
          [stageId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
