// Mocks generated by Mockito 5.4.4 from annotations
// in piano_tool/test/ui/import/review_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i4;
import 'dart:typed_data' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:piano_tool/data/ingestion_repository.dart' as _i2;
import 'package:piano_tool/models/level_models.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIngestionJobResult_0 extends _i1.SmartFake
    implements _i2.IngestionJobResult {
  _FakeIngestionJobResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IngestionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIngestionRepository extends _i1.Mock
    implements _i2.IngestionRepository {
  MockIngestionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> submitUpload(_i4.File? file) => (super.noSuchMethod(
        Invocation.method(
          #submitUpload,
          [file],
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #submitUpload,
            [file],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> submitYoutubeUrl(String? url) => (super.noSuchMethod(
        Invocation.method(
          #submitYoutubeUrl,
          [url],
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #submitYoutubeUrl,
            [url],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> submitRecording(_i6.Uint8List? audioBytes) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitRecording,
          [audioBytes],
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #submitRecording,
            [audioBytes],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<_i2.IngestionJobResult> pollJob(String? jobId) =>
      (super.noSuchMethod(
        Invocation.method(
          #pollJob,
          [jobId],
        ),
        returnValue:
            _i3.Future<_i2.IngestionJobResult>.value(_FakeIngestionJobResult_0(
          this,
          Invocation.method(
            #pollJob,
            [jobId],
          ),
        )),
      ) as _i3.Future<_i2.IngestionJobResult>);

  @override
  _i3.Future<void> cancelJob(String? jobId) => (super.noSuchMethod(
        Invocation.method(
          #cancelJob,
          [jobId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveLevel(_i7.LevelModel? level) => (super.noSuchMethod(
        Invocation.method(
          #saveLevel,
          [level],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i7.LevelModel>> listImportedLevels() => (super.noSuchMethod(
        Invocation.method(
          #listImportedLevels,
          [],
        ),
        returnValue: _i3.Future<List<_i7.LevelModel>>.value(<_i7.LevelModel>[]),
      ) as _i3.Future<List<_i7.LevelModel>>);

  @override
  _i3.Future<void> deleteImportedLevel(String? levelId) => (super.noSuchMethod(
        Invocation.method(
          #deleteImportedLevel,
          [levelId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
